# Generated by Django 2.1.7 on 2019-02-24 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('numero_archivo', models.IntegerField()),
                ('archivo', models.FileField(blank=True, upload_to='')),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaPortafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('red_social', models.CharField(max_length=50)),
                ('pagina_web', models.URLField(max_length=50)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('telefono', models.CharField(max_length=20)),
                ('pagina', models.CharField(default='Inicio', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContenidoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('numero_imagen', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, upload_to='')),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncluyeServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=60)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_proyecto', models.CharField(max_length=40)),
                ('titulo_inferior', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.CategoriaPortafolio')),
                ('colaboradores', models.ManyToManyField(to='portafolio.Colaborador')),
                ('imagenes', models.ManyToManyField(to='portafolio.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('sub_titulo', models.CharField(max_length=40)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.Categoria_post')),
                ('imagenes', models.ManyToManyField(to='portafolio.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitosServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito', models.CharField(max_length=60)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('costo', models.CharField(max_length=40)),
                ('modalidad', models.CharField(max_length=40)),
                ('lugar', models.CharField(max_length=40)),
                ('horario', models.CharField(max_length=40)),
                ('vigencia', models.IntegerField(default=1)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('archivos', models.ManyToManyField(to='portafolio.Archivo')),
                ('flayer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='TextoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_texto', models.CharField(max_length=40)),
                ('texto', models.TextField()),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textos', to='portafolio.Post')),
            ],
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('vigencia', models.IntegerField(default=1)),
                ('fecha_publicacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='portafolio.Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.Poll')),
                ('voted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='servicio',
            name='tipo_servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='portafolio.TipoServicio'),
        ),
        migrations.AddField(
            model_name='requisitosservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_servicio', to='portafolio.Servicio'),
        ),
        migrations.AddField(
            model_name='productosservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_servicio', to='portafolio.Servicio'),
        ),
        migrations.AddField(
            model_name='incluyeservicio',
            name='servicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Incluye_servicio', to='portafolio.Servicio'),
        ),
        migrations.AddField(
            model_name='contenidoservicio',
            name='servicio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contenido_servicio', to='portafolio.Servicio'),
        ),
        migrations.AddField(
            model_name='choice',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='portafolio.Poll'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('poll', 'voted_by')},
        ),
    ]
